// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_IKUKLz56GHfEHzO08MehtwDHan9s3uw',
    appId: '1:412115504586:android:3ef9c2a88782179c2e1333',
    messagingSenderId: '412115504586',
    projectId: 'zupadel2',
    storageBucket: 'zupadel2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwS8qa7KK85ibZQaHAoIy0_cG0iYAzFRw',
    appId: '1:412115504586:ios:1d9c8b2e2d6fc91b2e1333',
    messagingSenderId: '412115504586',
    projectId: 'zupadel2',
    storageBucket: 'zupadel2.firebasestorage.app',
    iosBundleId: 'com.example.zupadel',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxvu8zHy98pFZ3Yh5ilNGOtOvDWSLEZjU',
    appId: '1:412115504586:web:470bfd0261b2d2882e1333',
    messagingSenderId: '412115504586',
    projectId: 'zupadel2',
    authDomain: 'zupadel2.firebaseapp.com',
    storageBucket: 'zupadel2.firebasestorage.app',
    measurementId: 'G-71FPXNSCB0',
  );

}